### ISSUE TITLE
Allow requirements to be used as install tasks

### ISSUE THREAD

**Issue by shadcn** [apigee/requirement-drupal#3]
It would be helpful if a profile could mark a requirement as an install task such that the requirement could be completed during installation.

Example: The `apigee_devportal_kickstart` profile could mark  `Drupal\apigee_m10n\Plugin\Requirement\Requirement\ApigeeEdgeConnection` as a install task requirement such that it is presented as a step during installation.

This would help reduce code duplication in `apigee_devportal_kickstart` and `apigee` contrib modules.

**Comment by cnovak** [comment]
@arshad can you add more details to this ticket? Not sure what it is about.

**Comment by shadcn** [comment]
> @arshad can you add more details to this ticket? Not sure what it is about.

Updated.

**Comment by cnovak** [comment]
Thanks @arshad .   Our documentation says we are using the Drupal issue queue, want to move this over there and I will turn off issues in this GitHub project?

**Comment by shadcn** [comment]
Sure. I’ll move it.

**Comment by shadcn** [comment]
Moved to https://www.drupal.org/project/requirement/issues/3110019 (We can turn off issues here)
